### ISSUE TITLE
Fix date logic in Venue->findAllVenuesByProximity()

### ISSUE THREAD

**Issue by essboyer** [essboyer/Cheapskate#10]
We need to add logic to `Venue->findAllVenuesByProximity()` to the where query of the venue radius query to allow only loading of deals between now and 1 week from now.

Since deals are usually recurring, they don't have actual dates, they have the day number (where friday == 5, sunday == 1, etc). There is also the possibility of the deal being a weekly, bi-weekly, monthly, etc, so that needs to be taken into account as well.

**Comment by mikotoiii** [comment]
Just making a note of the sample SQL I'm using to pull information from the database in its current broken logic state.

SELECT
            v.id, (
                6371 * acos (
                                  cos(radians(45.271111))
                                * cos(radians(latitude))
                                * cos(radians(longitude) - radians(-66.059719))
                                + sin(radians(45.271111))
                                * sin(radians(latitude))
                )
            ) AS distance
            FROM venue as v
            WHERE v.id IN (SELECT DISTINCT venueId FROM event WHERE timeDay = 4)
								HAVING distance < 10
								ORDER BY distance

**Comment by mikotoiii** [comment]
So there's an issue that i've found in the determining of when an event is (it's unnoticable in the small scale, but in the large scale it is glaring).

If you have an event like the Christmas Boozeup, which happens yearly on Dec. 25, there is no point of reference to compare to for recursion as no dates are held in the database.

This also comes to the light when an event is between day x and day y. So things like weekend deals will trigger, but things like weekend deal for z week will not as there are no dates set (it will act like a recurring weekend deal).

**Comment by mikotoiii** [comment]
One thing that I was thinking also is that instead of putting logic in there to compensate for the dates, we can select the Venues by proximity only, then pass those results into another function that will select the proper events based on venues returned from this function and then do the date checking in that query. We'll still need a date function built into the DB as per above and #17, but this will allow us to properly limit things by proximity.

**Comment by mikotoiii** [comment]
Most of the logic is fixed now; however, the issue that I'm running into is that when there are no results returned, it's returning everything, which is what the original bug about results not on the proper days was about, we just didn't know it yet.

**Comment by mikotoiii** [comment]
Fixed in #18
