### ISSUE TITLE
Venue: Collect days with active deals per venue

### ISSUE THREAD

**Issue by essboyer** [essboyer/Cheapskate#15]
Add the ability to collect a list of the days of the week which have deals. This will make it easier for the JS to determine which days to create day blocks for.

I think this can be done while processing the results of collecting the active deals for the venue from the DB.

**Comment by mikotoiii** [comment]
These changes coincide with work that was done for #18, and are currently included in that PR.

Follows the existing format for finding days with events. This finds days with deals.

**Comment by mikotoiii** [comment]
Included in #18
